spring:
  application:
    name: "takehome"
  flyway:
    enabled: true
    baselineOnMigrate: true
    schema: country_api
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  cache:
    jcache:
      config: classpath:ehcache.xml

management:
  endpoints:
    web:
      exposure:
        include:  health,info,metrics
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  health:
    ratelimiters:
      enabled: true

server:
  error:
    include-message: always

graphql:
  api:
    url: https://countries.trevorblades.com/
  query:
    filepath: graphql/getContinentDetails.graphql

# Token expiration secret key (256 bit, Hex)
# Token expiration time in milliseconds (30 min = 1000 (milisec/sec) * 60 (sec/min) * 30 min)
jwtToken:
    secret-key: "462D4A614E645267556B58703273357638792F423F4428472B4B625065536856"
    expiration-time: 1800000

resilience4j:
  ratelimiter:
    instances:
      nonAuthCountryDataRateLimiter:
        allow-health-indicator-to-fail: true
        event-consumer-buffer-size: 50
        limit-for-period: 5
        limit-refresh-period: 1s
        register-health-indicator: true
        subscribe-for-events: true
        timeout-duration: 0s
      authCountryDataRateLimiter:
        allow-health-indicator-to-fail: true
        event-consumer-buffer-size: 50
        limit-for-period: 20
        limit-refresh-period: 1s
        register-health-indicator: true
        subscribe-for-events: true
        timeout-duration: 0s
    metrics:
      enabled: true