-- set schema 'country_api';

DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS continent;
DROP TABLE IF EXISTS api_user;

CREATE TABLE continent
(
    code VARCHAR(3)  NOT NULL,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_continent PRIMARY KEY (code)
);

ALTER TABLE continent
    ADD CONSTRAINT continent_code_idx UNIQUE (code);

CREATE TABLE country
(
    code           VARCHAR(3)   NOT NULL,
    name           VARCHAR(100) NOT NULL,
    continent_code VARCHAR(3)   NULL,
    CONSTRAINT pk_country PRIMARY KEY (code)
);

ALTER TABLE country
    ADD CONSTRAINT country_code_idx UNIQUE (code);

ALTER TABLE country
    ADD CONSTRAINT FK_COUNTRY_ON_CONTINENT_CODE FOREIGN KEY (continent_code) REFERENCES continent (code);

CREATE TABLE api_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(100)                            NOT NULL,
    last_name  VARCHAR(100)                            NOT NULL,
    email      VARCHAR(100)                            NOT NULL,
    role       VARCHAR(10),
    password   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_api_user PRIMARY KEY (id)
);